BIN = bin
OUT = out
SRC = src
INC = include

LDSCRIPT=$(SRC)/link.ld

PREFIX = aarch64-none-elf
CCBIN = ../$(PREFIX)/bin

OBJS := $(wildcard $(SRC)/*.[cS])
OBJS := $(patsubst $(SRC)/%.c, $(BIN)/%.o, $(OBJS))
OBJS := $(patsubst $(SRC)/%.S, $(BIN)/%.o, $(OBJS))

LIB = libpi
LIBINC = include
LIBPATH = ../$(LIB)

SPEED ?= -Og

TARGET ?= kernel.img

TARGETBASE = $(basename $(TARGET))

CC = $(CCBIN)/$(PREFIX)-gcc
CFLAGS = -ffreestanding -mcpu=cortex-a72 $(SPEED) -Wall -Wextra -Werror -I$(INC) -I$(LIBPATH)/$(LIBINC) -MD
ASFLAGS = -mcpu=cortex-a72 -Wall -Wextra -Werror -I$(INC) -I$(LIBPATH)/$(LIBINC)
LD = $(CCBIN)/$(PREFIX)-ld
LDFLAGS =
OCP = $(CCBIN)/$(PREFIX)-objcopy
ODMP = $(CCBIN)/$(PREFIX)-objdump

all: $(OUT)/$(TARGET) $(OUT)/$(TARGETBASE).list
clean:
	make -C $(LIBPATH) clean
	rm -rf $(BIN) $(OUT)

$(BIN):
	mkdir $(BIN)
$(OUT):
	mkdir $(OUT)

$(BIN)/%.o: $(SRC)/%.c | $(BIN)
	$(CC) $(CFLAGS) -c $< -o $@
$(BIN)/%.o: $(SRC)/%.S | $(BIN)
	$(CC) $(ASFLAGS) -c $< -o $@

$(LIBPATH)/$(LIB).a: FORCE
	$(MAKE) -C $(LIBPATH) -j$(shell nproc)

$(OUT)/$(TARGETBASE).elf: $(LDSCRIPT) $(OBJS) $(LIBPATH)/$(LIB).a | $(OUT)
	$(LD) $(LDFLAGS) -T $^ -o $@
$(OUT)/$(TARGET): $(OUT)/$(TARGETBASE).elf | $(OUT)
	$(OCP) -Obinary $< $@
$(OUT)/$(TARGETBASE).list: $(OUT)/$(TARGETBASE).elf | $(OUT)
	$(ODMP) -D $< > $@

-include $(OBJS:.o=.d)

.PHONY: clean all
.SILENT: $(BIN) $(OUT)
FORCE:
